services:
  - type: web
    name: anlix-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
